<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title><?= $artist['artist_name'] ?></title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1><?= $artist['artist_name'] ?></h1>
<div></div>
<?php

echo '<h2>' . $artist['artist_name'] . '</h2>';

foreach ($albumsArray as $album)
{
    echo '<h2><a href="/albums/' . $album['id'] . '">' . $album['album_name'] . '</a></h2>';
}

echo "<p>Back to <a href='/'>home</a></p>";

?>
</body>
</html>
